apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: base 
  releaseName: base 
  version: 1.13.3
  repo: https://istio-release.storage.googleapis.com/charts
  includeCRDs: true
  valuesInline:
    global:
      istioNamespace: istio
      configValidation: false
      istiod:
        enableAnalysis: true