apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: kiali-operator
  releaseName: kiali-operator
  version: 1.56.0
  repo: https://kiali.org/helm-charts
  includeCRDs: true
  valuesInline:
    enabled: true
    fullnameOverride: kiali

    istio_namespace: istio-system
    auth:
      strategy: anonymous
    deployment:
      service_type: LoadBalancer
    external_services:
      istio:
        component_status:
          components:
          - app_label: istiod
            is_core: true
            is_proxy: false
          - app_label: istio-ingressgateway
            is_core: true
            is_proxy: true
          - app_label: istio-eastwestgateway
            is_core: false
            is_proxy: true
          - app_label: istio-egressgateway
            is_core: false
            is_proxy: true
      grafana:
        auth:
          password: istio
          username: admin
        in_cluster_url: http://grafana:80
        url: http://grafana.localhost
      prometheus:
        url: http://prometheus:80
    server:
      port: 80