apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
helmCharts:
- name: grafana 
  releaseName: grafana 
  #version: 34.10.0
  repo: https://charts.helm.sh/stable
  valuesFile: values.yaml
  includeCRDs: true


