fullnameOverride: grafana
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
grafana.ini:
  server:
    domain: grafana.localhost

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
  # - type: Resource
  #   resource:
  #     name: memory
  #     targetAverageUtilization: 60

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Alertmanager
      type: alertmanager
      url: http://prometheus-alertmanager
      uid: alertmanager
      access: proxy
      jsonData:
        implementation: prometheus
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-stack:3100
      version: 1
      jsonData:
        alertmanagerUid: alertmanager
        maxLines: 5000
        timeout: "60"
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true
      jsonData:
        manageAlerts: true
        alertmanagerUid: alertmanager
notifiers:
  notifiers.yaml:
    notifiers:
      - name: prometheus-alertmanager
        type: prometheus-alertmanager
        uid: prometheus-alertmanager
        org_id: 1
        is_default: true
        settings:
          url: http://prometheus-alertmanager
    delete_notifiers: []


sidecar:
  plugins:
    enabled: true
  notifiers:
    enabled: false
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    folder: /var/lib/grafana/dashboards/external
    folderAnnotation: grafana.localhost/dashboard-folder
#      searchNamespace: ALL
    provider:
      disableDelete: false
      allowUiUpdates: true
      foldersFromFilesStructure: true
  datasources:
    enabled: false
    label: grafana_datasource
    labelValue: "1"

plugins:
  - grafana-piechart-panel

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'Kubernetes Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
    - name: 'alertmanager'
      orgId: 1
      folder: 'Alertmanager Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/alertmanager
    - name: 'argocd'
      orgId: 1
      folder: 'ArgoCD Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/argocd
    - name: 'github'
      orgId: 1
      folder: 'GitHub Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/github
    - name: 'istio'
      orgId: 1
      folder: 'Istio Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/istio
    - name: 'loki'
      orgId: 1
      folder: 'Loki Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/loki