apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: prometheus 
  releaseName: prometheus
  version: 14.9.1
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  valuesInline:
  prometheus:
    enabled: true
    fullnameOverride: prometheus

    alertmanager:
      fullnameOverride: prometheus-alertmanager
    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    nodeExporter:
      fullnameOverride: prometheus-node-exporter
    pushgateway:
      fullnameOverride: prometheus-pushgateway
      enabled: false
    server:
      fullnameOverride: prometheus
      service:
        type: LoadBalancer 