#nameOverride: "k8s"
alertmanager:
  tls:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager.localhost
    paths:
      - /
  config:
    receivers:
      # TODO: Add email receivers here.
      - name: "null"
  route:
    group_by: ['job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    receiver: email
    routes:
    - match:
        alertname: Watchdog
      receiver: 'null'
    - match:
        alertname: CPUThrottlingHigh
      receiver: 'null'
    - match:
        alertname: KubeMemoryOvercommit
      receiver: 'null'
    - match:
        alertname: KubeCPUOvercommit
      receiver: 'null'
    - match:
        alertname: KubeletTooManyPods
      receiver: 'null'
  alertmanagerSpec:
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    storage:
      volumeClaimTemplate:
        metadata:
          labels:
            storage: prometheus
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
prometheus:
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  tls:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.localhost
    paths:
      - /
  prometheusSpec:
    retention: 10d
    retentionSize: 1GB
    # Allow ServiceMonitors/PodMonitors from any namespace
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        metadata:
          labels:
            storage: prometheus
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi


grafana:
  tls:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.localhost
    path: /
  persistence:
    enabled: true

  plugins:
    - grafana-piechart-panel
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false