#nameOverride: "k8s"
alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.localhost
    paths:
      - /
  config:
    receivers:
      # TODO: Add email receivers here.
      - name: "null"
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          labels:
            storage: prometheus
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.localhost
    paths:
      - /
  prometheusSpec:
    retention: 10d
    retentionSize: 1GB
    # Allow ServiceMonitors/PodMonitors from any namespace
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        metadata:
          labels:
            storage: prometheus
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi


grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.localhost
    path: /
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi

prometheusOperator:
  admissionWebhooks:
    enabled: true
  tls:
    enabled: false