alertmanager:
  config:
    receivers:
      # TODO: Add email receivers here.
      - name: "null"
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          labels:
            storage: prometheus
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
prometheus:
  prometheusSpec:
    retention: 10d
    retentionSize: 1GB
    # Allow ServiceMonitors/PodMonitors from any namespace
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        metadata:
          labels:
            storage: prometheus
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
prometheusOperator:
  admissionWebhooks:
    enabled: false
grafana:
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi