#nameOverride: "k8s"
alertmanager:
  tls:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager.localhost
    paths:
      - /
  config:
    receivers:
      # TODO: Add email receivers here.
      - name: "null"
  alertmanagerSpec:
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    storage:
      volumeClaimTemplate:
        metadata:
          labels:
            storage: prometheus
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
prometheus:
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  tls:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.localhost
    paths:
      - /
  prometheusSpec:
    retention: 10d
    retentionSize: 1GB
    # Allow ServiceMonitors/PodMonitors from any namespace
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        metadata:
          labels:
            storage: prometheus
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi


grafana:
  tls:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.localhost
    path: /
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi
  plugins:
    - grafana-piechart-panel
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi

  sidecar:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi

  prometheusOperator:
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  priorityClassName: high-priority

  prometheus-node-exporter:
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 5m
      memory: 16Mi
  priorityClassName: high-priority

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false