nameOverride: prometheus-adapter

prometheus:
  url: "http://prometheus-operator-prometheus.monitoring.svc"
  port: 9090
resources: {}
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
rules:
  default: true
  custom:
    - seriesQuery: 'container_network_receive_bytes_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: { resource: "namespace" }
          pod: { resource: "pod" }
      name:
        matches: "^(.*)_total"
        as: "${1}"
      metricsQuery: "sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)"
