fullnameOverride: istiod
global:
  trustDomain: "lgsk8sp1.grupologos.local"
  proxy:
    clusterDomain: "lgsk8sp1.grupologos.local"
  # Resources for the sidecar.
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  autoscalingv2API: false
meshConfig:
  defaultConfig:
    discoveryAddress: istiod.istio-system.svc:15012
telemetry:
  enabled: true
  configValidation: false