apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: jaeger 
  releaseName: jaeger
  version: 0.47.0
  repo: https://jaeger-community.github.io/helm-charts
  includeCRDs: true