apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: grafana 
  releaseName: grafana
  version: 6.16.13
  repo: https://grafana.github.io/helm-charts
  includeCRDs: true
  valuesFile: values.yaml
