enabled: true
fullnameOverride: grafana

adminUser: admin
adminPassword: istio
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Alertmanager
      type: alertmanager
      file: http://prometheus-alertmanager
      uid: alertmanager
      access: proxy
      jsonData:
        implementation: prometheus
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      file: http://loki-stack:3100
      version: 1
      jsonData:
        alertmanagerUid: alertmanager
        maxLines: 5000
        timeout: "60"
    - name: Prometheus
      type: prometheus
      file: http://prometheus-server
      access: proxy
      isDefault: true
      jsonData:
        manageAlerts: true
        alertmanagerUid: alertmanager
notifiers:
  notifiers.yaml:
    notifiers:
      - name: prometheus-alertmanager
        type: prometheus-alertmanager
        uid: prometheus-alertmanager
        org_id: 1
        is_default: true
        settings:
          file: http://prometheus-alertmanager
    delete_notifiers: []


sidecar:
  plugins:
    enabled: true
  notifiers:
    enabled: false
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    folder: /var/lib/grafana/dashboards/external
    folderAnnotation: grafana.diegoluisi.eti.br/dashboard-folder
#      searchNamespace: ALL
    provider:
      disableDelete: false
      allowUiUpdates: true
      foldersFromFilesStructure: true
  datasources:
    enabled: false
    label: grafana_datasource
    labelValue: "1"


plugins:
  - grafana-piechart-panel

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'Kubernetes Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
    - name: 'alertmanager'
      orgId: 1
      folder: 'Alertmanager Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/alertmanager
    - name: 'istio'
      orgId: 1
      folder: 'Istio Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/istio
    - name: 'loki'
      orgId: 1
      folder: 'Loki Dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/loki
dashboards:
  default:
    core-dns:
      datasource: Prometheus
      file: "dashboards/kubernetes/core-dns.json"
    k8s-addons-starboard-operator:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s-addons-starboard-operator.json"
    k8s-system-api-server:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s-system-api-server.json"
    k8s-system-coredns:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s-system-coredns.json"
    k8s-views-global:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s-views-global.json"
    k8s-views-namespaces:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s-views-namespaces.json"
    k8s-views-nodes:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s-views-nodes.json"
    k8s-views-pods:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s-views-pods.json"
    k8s_views_global-kubernetes-views-global:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s_views_global-kubernetes-views-global.json"
    k8s_views_nodes-kubernetes-views-nodes:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s_views_nodes-kubernetes-views-nodes.json"
    k8s_views_ns-kubernetes-views-namespaces:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s_views_ns-kubernetes-views-namespaces.json"
    k8s_views_pods-kubernetes-views-pods:
      datasource: Prometheus
      file: "dashboards/kubernetes/k8s_views_pods-kubernetes-views-pods.json"
    node-exporter-full:
      datasource: Prometheus
      file: "dashboards/kubernetes/node-exporter-full.json"
  alertmanager:
    alertmanager-default:
      datasource: Prometheus
      file: "dashboards/alertmanager/alertmanager.json"
  loki:
    dashboard:
      datasource: Loki
      file: "dashboards/loki/loki_stack_monitoring_quortex.json"
  istio:
    istio-control-plane-dashboard:
      datasource: Prometheus
      file: "dashboards/istio/istio-control-plane-dashboard.json"
    istio-mesh-dashboard:
      datasource: Prometheus
      file: "dashboards/istio/istio-mesh-dashboard.json"
    istio-service-dashboard:
      datasource: Prometheus
      file: "dashboards/istio/istio-service-dashboard.json"
    istio-wasm-extension-dashboard:
      datasource: Prometheus
      file: "dashboards/istio/istio-wasm-extension-dashboard.json"
    istio-workload-dashboard:
      datasource: Prometheus
      file: "dashboards/istio/istio-workload-dashboard.json"