apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: argo-events 
  releaseName: argo-events 
  #version: 1.15.0
  repo: https://argoproj.github.io/argo-helm
  includeCRDs: true

