apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: prometheus 
  releaseName: prometheus 
  #version: 1.15.0
  repo: https://prometheus-community.github.io/helm-charts

