apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
# - create-pv-pvc.yaml
helmCharts:
- name: kube-prometheus-stack 
  releaseName: kube-prometheus-stack 
  version: 34.10.0
  repo: https://prometheus-community.github.io/helm-charts
  #includeCRDs: true
  valuesFile: values.yaml