apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: kube-prometheus-stack 
  releaseName: kube-prometheus-stack 
  version: 34.10.0
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.yaml
  patchesJson6902:
  - target:
      group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: "prometheuses.monitoring.coreos.com"
    patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          "argocd.argoproj.io/sync-options": "Replace=true" 