alertmanager:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: gluster
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
  ingress:
    enabled: true
    hosts:
      - alertmanager.localhost
    paths:
      - /

grafana:
  adminPassword: admin
  serviceMonitor:
    labels:
      release: kps
  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  ingress:
    enabled: true
    hosts:
      - grafana.localhost
    path: /

prometheus:
  prometheusSpec:
    retention: 3d

#    replicas: 2
#    podAntiAffinity: "hard"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  ingress:
    enabled: true
    hosts:
      - prometheus.localhost
    paths:
      - /

kubeEtcd:
  enabled: false

# Disable kube-controller-manager and kube-scheduler monitoring. See https://github.com/cablespaghetti/k3s-monitoring/issues/2
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false