

kube-prometheus-stack:
  #namespaceOverride: "monitoring"
  pushgateway:
    enabled: false
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - alertmanager.localhost
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
  grafana:
    adminPassword: gra@07@5A_@
    ingress:
      enabled: true
      hosts:
        - grafana.localhost
    persistence:
      type: pvc
      enabled: true
      accessModes: ["ReadWriteOnce"]
      size: 1Gi

  prometheus:
    thanosIngress:
      enabled: false
      hosts:
        - thanos-gateway.localhost
    ingress:
      enabled: true
      hosts:
        - prometheus.localhost
    prometheusSpec:
      # serviceMonitorSelector:
      #   matchLabels:
      #     prometheus: monitor
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi