namespaceOverride: "monitoring"

kube-prometheus-stack:
  pushgateway:
    enabled: false
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - alertmanager.localhost
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.localhost
  prometheus:
    thanosIngress:
      enabled: false
      hosts:
        - thanos-gateway.localhost
    ingress:
      enabled: true
      hosts:
        - prometheus.localhost
    prometheusSpec:
      # serviceMonitorSelector:
      #   matchLabels:
      #     prometheus: monitor
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi