apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: gateway 
  releaseName: gateway 
  #version: 1.15.0
  repo: https://istio-release.storage.googleapis.com/charts
  includeCRDs: true

