apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: loki-distributed
  includeCRDs: true
  releaseName: loki-distributed
  version: 0.56.7
  repo: https://grafana.github.io/helm-charts
  valuesInline:
    fullnameOverride: loki
    global:
      dnsService: coredns
      clusterDomain: localhost.local